dist: trusty
language: java
jdk: oraclejdk8
services:
  - mysql
before_install:
  - chmod +x mvnw
  - mysql -e 'CREATE DATABASE petclinic;'
  - mysql -u root -e "CREATE USER 'petclinic'@'localhost' IDENTIFIED BY 'petclinic';"
  - mysql -u root -e "GRANT ALL ON petclinic.* TO 'petclinic'@'localhost';"
script: mvn test -Dspring.profiles.active=mysql