dist: trusty
language: java
jdk: oraclejdk8
services:
  - mysql
before_install:
  - chmod +x mvnw
  - mysql -e 'CREATE DATABASE petclinic;'
  - mysql -u root -e "CREATE USER 'petclinic'@'localhost' IDENTIFIED BY 'petclinic';"
  - mysql -u root -e "GRANT ALL ON petclinic.* TO 'petclinic'@'localhost';"
addons:
  sonarcloud:
    organization: "carcotmed"
    token:
      secure: "Pupm67q+Y1LCxlHvURQh/agfButvk535/ErV0zUoHe4UyCjbdqcIWouLs4HJt9EqsZBHaBFP/NCZG3m4XBvQhYZfqA2Tk8TB/v5cfdn8958QaBuxIPc3eP4n+dGaGigZs+vcFx8xLWYoRzYBX1PLViNCrw+8ap6hRwF5s/ljI1ALLzgSu6Pp6VYekjd95MWnBZaYwOroxS5Mbh39y5YYo0VRZaptn/18JuljcmgT42KJGTaQIvvtkfqlJ12pm+8zGj/eAE/Gb8rkUEcBhnlO9/WF8FDSuxV+T09gwtFCHfQmC64ADN3IwOhZX+sbbmRug1JizgONSxOnA9Qr/V8HIfn4kajITe+Q1JIq//oB/TXzCmS3EHAdL9nuIOMp302ltAnwqItgxZo8jbt4iKUgcWZUgNqeWc+QEZBhNmK8CFUWaomNUfuJVhq4rr5byK3o/nN615aLDJcShH33yFw1jXZ1zGlwQGV88wQ9KrarcfEV01y1uC0uzf4zsC/ywJJ2ksXk3ZZ1QPAGLORVJ6P/WAkqXON/O5ECB/VBOKRVJkbMomIVd6slPcjRi9iJhkjmRArsFXr2wgiVdbD7g9URmykkuIGOKyaV1xjTIvYtFwuNPmB9LK62nNCr0GXhzFnY508IHHLCfHQppWVqX6qp8NzmoYYh9wSjLIWQHtDZ9u0="
      # encrypted value of your token

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Carcotmed_DP-1920-G1-02
#script: mvn test -Dspring.profiles.active=mysql
