dist: trusty
language: java
jdk: oraclejdk8
services:
- mysql
before_install:
- chmod +x mvnw
- mysql -e 'CREATE DATABASE petclinic;'
- mysql -u root -e "CREATE USER 'petclinic'@'localhost' IDENTIFIED BY 'petclinic';"
- mysql -u root -e "GRANT ALL ON petclinic.* TO 'petclinic'@'localhost';"
addons:
  sonarcloud:
    organization: carcotmed
    token:
      secure: Abv+EAb8r6uC0B3Crsaj8tIAkUggNhgCKnzE5mZ+x88Nh50hq6FMuRPVK/JF+hJwNwMAXNXDxw/kNKfe7NhEfgrKVwPnPVrwD0BjDL3x7Ib19Ry8QM4LJx11NtgidJjNqY5k6bLlsYfqf5wAi3+Oo5ysYZbL6/PYeAtWLwspaNpMePxpuAELz/hCZUmuo2e9jTcFWD6YS9uT8TQ6PNsVjP46+P5r7U58IA9NRHnG3Xvu8NtoAsNDlRLqOEvIZJCvjxsPQAj9N2FrrwgIOccPzTGqa1CIiwGSA1xmyrYelbVj7ETqGVrJXKdjK8SyekT2hZptDH1nVqWUhVXfuiCc0s0TZwBVIsVtVyhTNGp5KAVH/11UHqgCbX757rHD5CQgHq44hN3zD1Fr3L82Wewf/Ft/QvcCPUUF/GYKEvqk+ZHHT+xDd6IpuPRCMr/FdVlAQYN/jqu0bevFFCms9gfVv57Jq/JWAJph3hsqtUNOBqATLMVdxPSQH6HUAEF2K/wKpZ5jy1KwD1sua9EjDFctKirqRLuo+Ng4SNy11XwUHq2nAkm4WYUJHEbmaQ3wS5hu6jE/M0CQDtUCULY3UC1c+IwoLcNBhbpISKpmMA51mjMuTMOdnUmAGtzMPvmNuU+O/RMf0BzK7fKntFqOIRdo/xxngh9LVOlcYGaegQGb8iM=
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Carcotmed_DP-1920-G1-02