package generatedAssertions.customAssertions;

import org.assertj.core.api.AbstractObjectAssert;
import org.assertj.core.util.Objects;
import org.springframework.samples.petclinic.model.BaseEntity;

/**
 * {@link BaseEntity} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class BaseEntityAssert extends AbstractObjectAssert<BaseEntityAssert, BaseEntity> {

  /**
   * Creates a new <code>{@link BaseEntityAssert}</code> to make assertions on actual BaseEntity.
   * @param actual the BaseEntity we want to make assertions on.
   */
  public BaseEntityAssert(BaseEntity actual) {
    super(actual, BaseEntityAssert.class);
  }

  /**
   * An entry point for BaseEntityAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myBaseEntity)</code> and get specific assertion with code completion.
   * @param actual the BaseEntity we want to make assertions on.
   * @return a new <code>{@link BaseEntityAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static BaseEntityAssert assertThat(BaseEntity actual) {
    return new BaseEntityAssert(actual);
  }

  /**
   * Verifies that the actual BaseEntity's id is equal to the given one.
   * @param id the given id to compare the actual BaseEntity's id to.
   * @return this assertion object.
   * @throws AssertionError - if the actual BaseEntity's id is not equal to the given one.
   */
  public BaseEntityAssert hasId(Integer id) {
    // check that actual BaseEntity we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting id of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    Integer actualId = actual.getId();
    if (!Objects.areEqual(actualId, id)) {
      failWithMessage(assertjErrorMessage, actual, id, actualId);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual BaseEntity is new.
   * @return this assertion object.
   * @throws AssertionError - if the actual BaseEntity is not new.
   */
  public BaseEntityAssert isNew() {
    // check that actual BaseEntity we want to make assertions on is not null.
    isNotNull();

    // check that property call/field access is true
    if (!actual.isNew()) {
      failWithMessage("\nExpecting that actual BaseEntity is new but is not.");
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual BaseEntity is not new.
   * @return this assertion object.
   * @throws AssertionError - if the actual BaseEntity is new.
   */
  public BaseEntityAssert isNotNew() {
    // check that actual BaseEntity we want to make assertions on is not null.
    isNotNull();

    // check that property call/field access is false
    if (actual.isNew()) {
      failWithMessage("\nExpecting that actual BaseEntity is not new but is.");
    }

    // return the current assertion for method chaining
    return this;
  }

}
