package generatedAssertions.customAssertions;

import org.assertj.core.api.AbstractObjectAssert;
import org.assertj.core.util.Objects;
import org.springframework.samples.petclinic.model.NamedEntity;

/**
 * {@link NamedEntity} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class NamedEntityAssert extends AbstractObjectAssert<NamedEntityAssert, NamedEntity> {

  /**
   * Creates a new <code>{@link NamedEntityAssert}</code> to make assertions on actual NamedEntity.
   * @param actual the NamedEntity we want to make assertions on.
   */
  public NamedEntityAssert(NamedEntity actual) {
    super(actual, NamedEntityAssert.class);
  }

  /**
   * An entry point for NamedEntityAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myNamedEntity)</code> and get specific assertion with code completion.
   * @param actual the NamedEntity we want to make assertions on.
   * @return a new <code>{@link NamedEntityAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static NamedEntityAssert assertThat(NamedEntity actual) {
    return new NamedEntityAssert(actual);
  }

  /**
   * Verifies that the actual NamedEntity's id is equal to the given one.
   * @param id the given id to compare the actual NamedEntity's id to.
   * @return this assertion object.
   * @throws AssertionError - if the actual NamedEntity's id is not equal to the given one.
   */
  public NamedEntityAssert hasId(Integer id) {
    // check that actual NamedEntity we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting id of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    Integer actualId = actual.getId();
    if (!Objects.areEqual(actualId, id)) {
      failWithMessage(assertjErrorMessage, actual, id, actualId);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual NamedEntity's name is equal to the given one.
   * @param name the given name to compare the actual NamedEntity's name to.
   * @return this assertion object.
   * @throws AssertionError - if the actual NamedEntity's name is not equal to the given one.
   */
  public NamedEntityAssert hasName(String name) {
    // check that actual NamedEntity we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting name of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualName = actual.getName();
    if (!Objects.areEqual(actualName, name)) {
      failWithMessage(assertjErrorMessage, actual, name, actualName);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual NamedEntity is new.
   * @return this assertion object.
   * @throws AssertionError - if the actual NamedEntity is not new.
   */
  public NamedEntityAssert isNew() {
    // check that actual NamedEntity we want to make assertions on is not null.
    isNotNull();

    // check that property call/field access is true
    if (!actual.isNew()) {
      failWithMessage("\nExpecting that actual NamedEntity is new but is not.");
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual NamedEntity is not new.
   * @return this assertion object.
   * @throws AssertionError - if the actual NamedEntity is new.
   */
  public NamedEntityAssert isNotNew() {
    // check that actual NamedEntity we want to make assertions on is not null.
    isNotNull();

    // check that property call/field access is false
    if (actual.isNew()) {
      failWithMessage("\nExpecting that actual NamedEntity is not new but is.");
    }

    // return the current assertion for method chaining
    return this;
  }

}
