package generatedAssertions.customAssertions;

import org.assertj.core.api.AbstractObjectAssert;
import org.assertj.core.util.Objects;
import org.springframework.samples.petclinic.model.Provider;

/**
 * {@link Provider} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public class ProviderAssert extends AbstractObjectAssert<ProviderAssert, Provider> {

  /**
   * Creates a new <code>{@link ProviderAssert}</code> to make assertions on actual Provider.
   * @param actual the Provider we want to make assertions on.
   */
  public ProviderAssert(Provider actual) {
    super(actual, ProviderAssert.class);
  }

  /**
   * An entry point for ProviderAssert to follow AssertJ standard <code>assertThat()</code> statements.<br>
   * With a static import, one can write directly: <code>assertThat(myProvider)</code> and get specific assertion with code completion.
   * @param actual the Provider we want to make assertions on.
   * @return a new <code>{@link ProviderAssert}</code>
   */
  @org.assertj.core.util.CheckReturnValue
  public static ProviderAssert assertThat(Provider actual) {
    return new ProviderAssert(actual);
  }

  /**
   * Verifies that the actual Provider's address is equal to the given one.
   * @param address the given address to compare the actual Provider's address to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Provider's address is not equal to the given one.
   */
  public ProviderAssert hasAddress(String address) {
    // check that actual Provider we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting address of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualAddress = actual.getAddress();
    if (!Objects.areEqual(actualAddress, address)) {
      failWithMessage(assertjErrorMessage, actual, address, actualAddress);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual Provider's email is equal to the given one.
   * @param email the given email to compare the actual Provider's email to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Provider's email is not equal to the given one.
   */
  public ProviderAssert hasEmail(String email) {
    // check that actual Provider we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting email of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualEmail = actual.getEmail();
    if (!Objects.areEqual(actualEmail, email)) {
      failWithMessage(assertjErrorMessage, actual, email, actualEmail);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual Provider's id is equal to the given one.
   * @param id the given id to compare the actual Provider's id to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Provider's id is not equal to the given one.
   */
  public ProviderAssert hasId(Integer id) {
    // check that actual Provider we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting id of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    Integer actualId = actual.getId();
    if (!Objects.areEqual(actualId, id)) {
      failWithMessage(assertjErrorMessage, actual, id, actualId);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual Provider's name is equal to the given one.
   * @param name the given name to compare the actual Provider's name to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Provider's name is not equal to the given one.
   */
  public ProviderAssert hasName(String name) {
    // check that actual Provider we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting name of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualName = actual.getName();
    if (!Objects.areEqual(actualName, name)) {
      failWithMessage(assertjErrorMessage, actual, name, actualName);
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual Provider is new.
   * @return this assertion object.
   * @throws AssertionError - if the actual Provider is not new.
   */
  public ProviderAssert isNew() {
    // check that actual Provider we want to make assertions on is not null.
    isNotNull();

    // check that property call/field access is true
    if (!actual.isNew()) {
      failWithMessage("\nExpecting that actual Provider is new but is not.");
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual Provider is not new.
   * @return this assertion object.
   * @throws AssertionError - if the actual Provider is new.
   */
  public ProviderAssert isNotNew() {
    // check that actual Provider we want to make assertions on is not null.
    isNotNull();

    // check that property call/field access is false
    if (actual.isNew()) {
      failWithMessage("\nExpecting that actual Provider is not new but is.");
    }

    // return the current assertion for method chaining
    return this;
  }

  /**
   * Verifies that the actual Provider's phone is equal to the given one.
   * @param phone the given phone to compare the actual Provider's phone to.
   * @return this assertion object.
   * @throws AssertionError - if the actual Provider's phone is not equal to the given one.
   */
  public ProviderAssert hasPhone(String phone) {
    // check that actual Provider we want to make assertions on is not null.
    isNotNull();

    // overrides the default error message with a more explicit one
    String assertjErrorMessage = "\nExpecting phone of:\n  <%s>\nto be:\n  <%s>\nbut was:\n  <%s>";

    // null safe check
    String actualPhone = actual.getPhone();
    if (!Objects.areEqual(actualPhone, phone)) {
      failWithMessage(assertjErrorMessage, actual, phone, actualPhone);
    }

    // return the current assertion for method chaining
    return this;
  }

}
